# Generated by Django 4.1.7 on 2023-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Leave this blank.Auto fill enabled.', null=True)),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('is_draft', models.BooleanField(default=True, help_text="Do not turn this to false if you haven't througly review your the aritcle")),
                ('posted_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
