# Generated by Django 4.1.7 on 2023-03-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletter',
            new_name='Newsletter',
        ),
    ]
