# Generated by Django 4.1.7 on 2023-03-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='adress',
            new_name='address',
        ),
    ]
